### ISSUE TITLE
Script does not support non-eth0 interface names (e.g., ens160)

### ISSUE THREAD

**Issue by develfishere** [kalilovers/LightKnightBBR#3]
Currently, the script is hardcoded to work only with the eth0 interface. This creates a limitation for systems using different network interface naming conventions, such as ens160 or others.

Steps to reproduce:

    Run the script on a system where the primary network interface is named ens160 (or anything other than eth0).
    Observe that the script fails to recognize or interact with the interface.

Expected behavior:

The script should dynamically detect or support custom interface names beyond eth0, such as ens160 or any interface name used by the system.

Suggested Solution:

    Modify the script to dynamically detect the network interface(s) in use, or provide an option to specify the interface name manually.
    Consider using system commands like ip link show or ifconfig to list available interfaces.

**Comment by kalilovers** [comment]
> Currently, the script is hardcoded to work only with the eth0 interface. This creates a limitation for systems using different network interface naming conventions, such as ens160 or others.
> 
> Steps to reproduce:
> 
> ```
> Run the script on a system where the primary network interface is named ens160 (or anything other than eth0).
> Observe that the script fails to recognize or interact with the interface.
> ```
> 
> Expected behavior:
> 
> The script should dynamically detect or support custom interface names beyond eth0, such as ens160 or any interface name used by the system.
> 
> Suggested Solution:
> 
> ```
> Modify the script to dynamically detect the network interface(s) in use, or provide an option to specify the interface name manually.
> Consider using system commands like ip link show or ifconfig to list available interfaces.
> ```

Thank you, dear friend. During the last two days, I was fixing things, and this item was also fixed and now it has been updated.

**Comment by kalilovers** [comment]
I made a lot of changes, check out the new update, if there was any problem, it would be a pleasure to let you know

**Comment by develfishere** [comment]
Hi,

Thanks for adding CAKE traffic control—it was a great idea! I checked the compatibility concern and didn't notice any issues. Everything is running smoothly.

**Comment by kalilovers** [comment]
> Hi,
> 
> Thanks for adding CAKE traffic control—it was a great idea! I checked the compatibility concern and didn't notice any issues. Everything is running smoothly.
> 
> 

Hahahahaha, I'm glad that it solved one of your needs

**Comment by develfishere** [comment]
surely it did!

**Comment by develfishere** [comment]
Bad news!

i ran the script on one of my servers (Digital Ocean basic droplet) to enable cake traffic control and encountered this error:
/etc/systemd/system/qdisc-setup.service:7: Unbalanced quoting, ignoring: "/bin/sh -c '/sbin/tc qdisc replace dev eth0 root cake"
the same error happens for fq and fq_codel tc algorithms
if you need more information, please let me know!

**Comment by kalilovers** [comment]
> Bad news!
> 
> i ran the script on one of my servers (Digital Ocean basic droplet) to enable cake traffic control and encountered this error: /etc/systemd/system/qdisc-setup.service:7: Unbalanced quoting, ignoring: "/bin/sh -c '/sbin/tc qdisc replace dev eth0 root cake" the same error happens for fq and fq_codel tc algorithms if you need more information, please let me know!

thank you very much
Please tell me the version of the operating system that is installed on your server
Also, if possible, send a screenshot of the part you are running and the error is displayed, along with the error text.
Then, if possible, send after executing the command... after hiding the private parts

**Comment by develfishere** [comment]
I’m running Ubuntu 24 on my server, and before providing the information you asked for, I think I may have identified the problem. 

My server has multiple interfaces (like eth0, eth1, and local interfaces), and this caused the qdisc-setup.service file to have several lines after the Exec section, which led to errors in the service file. To fix it, I moved that part into a separate .sh file and updated the Exec section to point to this script. The error went away after that! However, when I checked with the "tc qdisc" command, it looks like none of my interfaces are using the cake queuing algorithm and those commands did not apply.

**Comment by develfishere** [comment]
I will send logs here, if helps!

here is the log of script after selecting setup cakePlus :

`
Checking the compatibility of operating system and kernel for Cake...
The kernel version is compatible with Cake and BBR.
Checking and installing required packages...
All required packages are installed.
Deleting old files and setting new (+Backup)...
The old sysctl.conf file was deleted and backed up.
Setting up BBR...
Activating ECN persistently...
net.ipv4.tcp_ecn = 1
ECN activated and will remain active after reboot.
ECN has been activated with BBR.
net.ipv4.tcp_ecn = 1
net.core.default_qdisc = cake
net.ipv4.tcp_congestion_control = bbr
BBR settings applied.
Setting the queuing algorithm on all network interfaces...
The cake queuing algorithm was set on the eth0 interface.
The cake queuing algorithm was set on the veth8467d7b interface.
The cake queuing algorithm was set on the iran1config2 interface.
The cake queuing algorithm was set on the warp interface.
The cake queuing algorithm was set on the iran2config2 interface.
The cake queuing algorithm was set on the iran3config2 interface.
The cake queuing algorithm was set on the iran4config2 interface.
The cake queuing algorithm was set on the iran5config2 interface.
The cake queuing algorithm was set on the eth1 interface.
The cake queuing algorithm was set on the sit0 interface.
The cake queuing algorithm was set on the docker0 interface.
Creating systemd service to preserve qdisc settings after reboot on all interfaces...
Failed to start qdisc-setup.service: Unit qdisc-setup.service has a bad unit file setting.
See system logs and 'systemctl status qdisc-setup.service' for details.
The systemd service was successfully created and activated for all interfaces.
`

and here is the systemd file content:
`
[Unit]
Description=Set qdisc cake on all network interfaces
After=network.target

[Service]
Type=oneshot
ExecStart=/bin/sh -c '/sbin/tc qdisc replace dev eth0 root cake
/sbin/tc qdisc replace dev veth8467d7b root cake
/sbin/tc qdisc replace dev iran1config2 root cake
/sbin/tc qdisc replace dev warp root cake
/sbin/tc qdisc replace dev iran2config2 root cake
/sbin/tc qdisc replace dev iran3config2 root cake
/sbin/tc qdisc replace dev iran4config2 root cake
/sbin/tc qdisc replace dev iran5config2 root cake
/sbin/tc qdisc replace dev eth1 root cake
/sbin/tc qdisc replace dev sit0 root cake
/sbin/tc qdisc replace dev docker0 root cake'
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
`

**Comment by kalilovers** [comment]
> Bad news!
> 
> i ran the script on one of my servers (Digital Ocean basic droplet) to enable cake traffic control and encountered this error: /etc/systemd/system/qdisc-setup.service:7: Unbalanced quoting, ignoring: "/bin/sh -c '/sbin/tc qdisc replace dev eth0 root cake" the same error happens for fq and fq_codel tc algorithms if you need more information, please let me know!

Thank you very much my friend :)
Before checking the rest of the data you sent, I made a change according to the first problem you had. Please test again. In fact, this can be due to the existence of several different interfaces

**Comment by develfishere** [comment]
You're very welcome! Thank you so much for the quick solution! Yes, all the issues have been resolved, and everything is working perfectly now!

**Comment by kalilovers** [comment]
> You're very welcome! Thank you so much for the quick solution! Yes, all the issues have been resolved, and everything is working perfectly now!

You're welcome, my friend, if there is a problem with the script, I would appreciate it if you let me know after further investigation and some certainty that the problem is with the script.

**Comment by develfishere** [comment]
Thanks! I’ll make sure to do that. If I find any problems after more testing and I’m sure it's because of the script, I’ll let you know. Also, if you need any help, I’d be happy to contribute!
