### ISSUE TITLE
روی کدام سرور باید نصب کرد ؟

### ISSUE THREAD

**Issue by TiamaaShah** [kalilovers/LightKnightBBR#4]
درود بر شما
میخواستم بدونم که این اسکریپت را باید روی همه سرورهایی که به هم تانل شدن نصب کرد یا فقط کافیست که روی سرورهای ایران نصب کنیم و احتیاجی به نصب روی سرورهای خارج نیست ؟

**Comment by kalilovers** [comment]
درود همچنین . بستگی داره به استفادتون اگر تانل هست و دو سرور بهم متصله به نظرم بهتره توی هردو ست بشه و اگر شد حتما مشابه هم باشه تا الگوریتم ها مغایرت نداشته باشن و خیلی هماهنگ تر ترافیک صف بندی بشه و.. . در کل توصیه میکنم از یه متد مثلا bbr fq_codel توی هردو سرور استفاده کنید و فرق نداشته باشن (اگر روی یکی نصب بشه حتما سرور دوم یه الگوریتم پیشفرض داره که میتونیم بگیم ممکنه با سرور بهینه و الگوریتم متفاوتش خیلی کیفیت مناسبی به دست نیارید)

**Comment by TiamaaShah** [comment]
با تشکر از شما
